### ISSUE TITLE
Regarding README.md

### ISSUE THREAD

**Issue by the-amazing-atharva** [AIOCodeBase/GFGPOTD#572]
@ImSaMPro  I would like to be assigned and work on README of the repository.
I am a beginner, please let me know if there is a better way to ask to work on the repository

**Comment by ImSaMPro** [comment]
Hi @the-amazing-atharva ,
You can comment on one the exsisting issue you would like to contribute and if no one else is assigned to it then you will be assign to it.

**Comment by the-amazing-atharva** [comment]
Thanks for the reply !!

Sorry if this was the wrong way to raise an issue, I am new to Github

Looking forward to contribute in Feb !

**Comment by ImSaMPro** [comment]
@the-amazing-atharva , That's completely ok!
